name: Run CI
on:
  pull_request:
    types: [opened, reopened]
jobs:
  pull_request_action:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: npm i
      - name: Compiling Typescript files
        run: npm run build
      - name: Starting app
        run: npm start
      - name: Running linter
        run: npm run lint
      - name: Running tests
        run: npm run test
